swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
# here host not needed because it initialises in app.js programmatically from
#host: localhost:10010890898
#host: localhost:52107
host: a127-hello-world.herokuapp.com
# basePath prefixes all resource paths 
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: {}
x-a127-services: {}
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    x-a127-apply: {}
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /register:
    x-swagger-router-controller: users
    x-a127-apply: {}
    post:
      description: Registering new user
      operationId: register
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: registerInfo 
          in: body
          description: Registration User Info
          required: true
          schema:
            $ref: '#/definitions/RegisterInfo'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /login:
    x-swagger-router-controller: users
    x-a127-apply: {}
    post:
      description: User login
      operationId: login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: loginInfo 
          in: body
          description: User credentials for login
          required: true
          schema:
            $ref: '#/definitions/LoginInfo'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    type: string
  ErrorResponse:
    type: string
  RegisterInfo:
    description: Object for new user registration data 
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
    required:
      - email
      - password
  LoginInfo:
    description: User credentials for login 
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
    required:
      - email
      - password
