validateResponse: true
docEndpoints:
  raw: /swagger        # expose the swagger JSON and YAML at this endpoint
#  docs: /swagger-docs  # expose swagger-docs browser UI on this endpoint
ui:
  swaggerUi: '/api/ui'
  apiDocs: '/api/docs'

storage:
  secret: 'myapidbmongo'
  database: 'mongodb://wasya:123@ds019123.mlab.com:19123/apigee-api'

